codes = {
    "en": "en-US",
    "es": "es-US",
    "fr": "fr-FR",
    "it": "it-IT",
    "de": "de-DE",
    "nl": "nl-NL",
    "pt": "pt-BR",
    "sv": "sv-SE",
    "no": "no-NO",
    "ar": "ar-IL",
    "ru": "ru-RU",
    "ja": "ja-JP",
    "zh-cn": "cmn-Hans-CN",
    "zh-tw": "cmn-Hant-TW",
    "ko": "ko-KR",
}